#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

echo "Generating mac files..."

cd ../UCN-build/	# these two 'cd' should accomplish the same thing
#cd ${UCNA_BASE}/UCN-build/

echo "Files being saved in "
pwd

##### Edit these variables to generate the script 	#####
geom=2012-2013	#C = 2010, also 2011-2012 is ok
useSrcHolder=false
ptclType=external	# options: external, Sn113, Ce139, Bi207
beta=A_0_b_0		# anything. But if using external, label as Base or Fierz. Else, say Source
input=/home/xuansun/Documents/ucna_g4_2.1/UCN/UK_EventGen_2016/Evts_Files/FierzWork_2011-2013/2012-2013_geom_events/A_0_b_0
output=UCNASimOutput
nEvts=1000000
##### 							#####

rm xuan_geantgen*.mac	# get rid of any .mac files already in the directory
rm GNUParallel_commands.txt

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas
for ((x = 0; x < 20; x = x + 1))

do

sed 's/REPLACEWITHGEOMETRY/'$geom'/g' master_geantgen.mac > xuan_geantgen_$x.mac
# this -i seems to suppress printing out the file to screen. Use it.
sed -i 's/REPLACEWITHUSESOURCEHOLDER/'$useSrcHolder'/g' xuan_geantgen_$x.mac
sed -i 's/REPLACEWITHPTCLTYPE/'$ptclType'/g' xuan_geantgen_$x.mac
# use the | delimiter instead of / since you need to insert a path with "/" characters
sed -i 's|REPLACEWITHINPUTFILE|'$input\Evts_$x\.root'|g' xuan_geantgen_$x.mac
sed -i 's/REPLACEWITHOUTPUTFILE/'$output\_$ptclType\_$beta\_$geom'-Geom'\_$x\.txt'/g' xuan_geantgen_$x.mac
sed -i 's/REPLACEWITHNUMBEREVENTS/'$nEvts'/g' xuan_geantgen_$x.mac

# note the > means pipe to file, >> means append. Use > here
echo './ucn xuan_geantgen_'$x'.mac >> g4_run_'$x'.txt' >> GNUParallel_commands.txt

done

echo "Done running bash script"
